-- CreateTable
CREATE TABLE `withdrawal_audit` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_email_hash` CHAR(64) NOT NULL,
    `reason_type` ENUM('LOW_FREQUENCY', 'MISSING_FEATURE', 'INCONVENIENT', 'PRIVACY_CONCERN', 'SWITCHING_SERVICE', 'OTHER') NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
